https://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/?vgnextoid=eb8e993ae322b610VgnVCM1000001d4a900aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD&vgnextfmt=default

https://datosabiertos.malaga.eu/en/dataset/monumentos/resource/89bba578-b91b-4aff-92bc-c950d0e5b5b2
https://datosabiertos.malaga.eu/en/dataset/monumentos/resource/5dd56c7f-402d-4664-bf7c-432f6726bdcc

Las consultas con GeoSPARQL sólo sirven para consultas con datos almacenados localmente (debo mirar cómo almacenar localmente las coordenadas). Para consultas a servicios externos, DBpedia o Wikidata, no sirve. Para encontrar el monumento de mi ontología en Wikidata mediante sus coordenadas, debo hacerlo de forma parecida a: FILTER(ABS(?latitud - 40.40963497841015) < 0.001


DBpedia:
Esta es la antigua que por alguna razón no funciona (no sé si han cambiado algo en DBpedia):
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT distinct ?Monumentos ?abstract ?architect ?image ?autor ?lat ?long
WHERE {
?Monumentos dcterms:subject <http://es.dbpedia.org/resource/Categoría:Monumentos_conmemorativos_en_Madrid> .
    OPTIONAL { ?Monumentos dbo:abstract ?abstract}
    OPTIONAL { ?Monumentos dbo:architect ?architect}
    OPTIONAL { ?Monumentos prop-es:imagen ?image}
    OPTIONAL { ?Monumentos prop-es:autor ?autor}
    OPTIONAL { ?Monumentos geo:lat ?lat }
    OPTIONAL { ?Monumentos geo:long ?long }
}


Nueva consulta:
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX prop-es: <http://es.dbpedia.org/property/>

SELECT ?monumento ?descripcion ?autor ?lat ?long
WHERE {
	?monumento a dbo:Monument;
	dbo:location dbr:Madrid ;
	dbo:abstract ?descripcion .
	OPTIONAL { ?monumento dbo:architect ?autor . } 
        OPTIONAL { ?Monumento geo:lat ?lat }
        OPTIONAL { ?Monumento geo:long ?long }
	FILTER (lang(?descripcion) = "es")
}


Wikidata:

Consulta para monumentos y estatuas:
SELECT ?monumento ?monumentoLabel ?coordenadas ?autor ?autorLabel ?bibliografia ?bibliografiaLabel
WHERE {
  ?monumento wdt:P31 ?tipo;          # Instancia de tipo
            wdt:P131 wd:Q2807.       # Ubicado en Madrid

  VALUES ?tipo { wd:Q4989906 wd:Q179700 }  # Filtrar por Monumento y Estatua
  
  OPTIONAL { ?monumento wdt:P625 ?coordenadas. }    # Coordenadas (opcional)
  OPTIONAL { ?monumento wdt:P84 ?autor. }            # Autor o arquitecto (opcional)

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],es". }
}

La misma consulta de Apache Jena:
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX geof: <http://www.opengis.net/ont/geosparql#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT ?monumento ?monumentoLabel ?coordenadas ?autor ?autorLabel ?bibliografia ?bibliografiaLabel
WHERE {
  SERVICE <https://query.wikidata.org/sparql> { 
    ?monumento wdt:P31 ?tipo;          # Instancia de tipo
            wdt:P131 wd:Q2807.       # Ubicado en Madrid

  VALUES ?tipo { wd:Q4989906 wd:Q179700 }  # Filtrar por Monumento y Estatua
  
  OPTIONAL { ?monumento wdt:P625 ?coordenadas. }    # Coordenadas (opcional)
  OPTIONAL { ?monumento wdt:P84 ?autor. }            # Autor o arquitecto (opcional)

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],es". }
}
}

Forma chunga de hacerlo vía coordenadas (deben ser exactamente las mismas que almacena Wikidata):
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX geof: <http://www.opengis.net/ont/geosparql#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT ?monumento ?coordenadas ?autor ?tipo
WHERE {
  SERVICE <https://query.wikidata.org/sparql> { 
      ?monumento wdt:P31 ?tipo;        
              wdt:P131 wd:Q2807. # Location, we know for sure the city

    VALUES ?tipo { wd:Q4989906 wd:Q179700 }  # Filter by monument and statue

    OPTIONAL { ?monumento wdt:P625 ?coordenadas. }    # Coordenadas (optional)
    OPTIONAL { ?monumento wdt:P84 ?autor. }  # Author or arquitect (optional)
    
    FILTER(CONTAINS(STR(?coordenadas), "-3.688916 40.409635")) # Filtro de coordenadas aproximadas

    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],es". }
  }
}

También puedo hacerlo por el catalogCode (es el campo PK del CSV), e incluso por describedAtURL:
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX geof: <http://www.opengis.net/ont/geosparql#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT ?monumento ?coordenadas ?describedAtURL ?catalogCode ?autor ?tipo
WHERE {
  SERVICE <https://query.wikidata.org/sparql> { 
      ?monumento wdt:P31 ?tipo;        
              wdt:P131 wd:Q2807. # Location, we know for sure the city

    VALUES ?tipo { wd:Q4989906 wd:Q179700 }  # Filter by monument and statue

    OPTIONAL { ?monumento wdt:P625 ?coordenadas. }    # Coordenadas (optional)
    OPTIONAL { ?monumento wdt:P84 ?autor. }  # Author or arquitect (optional)
    OPTIONAL { ?monumento wdt:P973 ?describedAtURL }
    OPTIONAL { ?monumento wdt:P528 ?catalogCode }

    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],es". }
  }
}
ORDER BY ?catalogCode

